"""offers table

Revision ID: c4b58b6046da
Revises: eeda057181f0
Create Date: 2024-04-22 16:27:59.430447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b58b6046da'
down_revision = 'eeda057181f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Withdrawn'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_user_id'))
        batch_op.drop_index(batch_op.f('ix_offer_updated_at'))
        batch_op.drop_index(batch_op.f('ix_offer_request_id'))
        batch_op.drop_index(batch_op.f('ix_offer_created_at'))

    op.drop_table('offer')
    # ### end Alembic commands ###
