"""requests table

Revision ID: eeda057181f0
Revises: 2c61e7ccf9ef
Create Date: 2024-04-22 15:03:54.675598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeda057181f0'
down_revision = '2c61e7ccf9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Closed', 'Pending', 'Completed'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_request_updated_at'))
        batch_op.drop_index(batch_op.f('ix_request_created_at'))

    op.drop_table('request')
    # ### end Alembic commands ###
